# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Techlead Handbook
subtitle: Uma ajuda jornada de se tornar um líder 
email: marciohariki@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Uma ajuda jornada de se tornar um líder 
baseurl: ""
url: "https://techlead-handbook.hariki-labs.com"
twitter_username: marciohariki
github_username:  marciohariki
repository: marciohariki/techlead-handbook.github.io

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed

# =============
# Theme config
# =============
minimal_mistakes_skin: "dark"
search: true
breadcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : "/"

defaults:
  # resources
  - scope:
      path: ""
      type: default
    values:
      layout: single
      author_profile: true
