name: S3 Deploy
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Build
          uses: jerryjvl/jekyll-build-action@v1

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: _site
            bucket: techlead-handbook.hariki-labs.com
            bucket-region: sa-east-1
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true